version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend  # This sets the container name
    expose:
      - "8000"
    ports:
      - "8000:8000"  # Exposes port 8000 on the host to port 8000 in the container
    volumes:
      - ./backend:/app # Mount the current directory to /app in the container
    networks:
      - app-network
 #   environment:
  #     - API_KEY=your_api_key_here


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    expose:
      - "3000"
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge